"""Tests for ``bin/generate-skills``.

All tests use ``tmp_path`` and ``--target-dir`` for isolation. No test
mutates the real ``~/.claude/`` tree.

Strategy: copy ``bin/generate-skills`` into a temporary repo root that we
populate with controlled fixtures, then invoke it as a subprocess with
``--target-dir`` pointing at another tmp dir. This exercises the script
exactly as a user would run it.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT_PATH = REPO_ROOT / 'bin' / 'generate-skills'


def _make_repo(tmp_path: Path) -> Path:
    """Create a minimal diecast-shaped repo with our script copied in."""
    repo = tmp_path / 'diecast'
    (repo / 'bin').mkdir(parents=True)
    (repo / 'agents').mkdir()
    (repo / 'skills' / 'claude-code').mkdir(parents=True)
    shutil.copy2(SCRIPT_PATH, repo / 'bin' / 'generate-skills')
    return repo


def _run(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(repo / 'bin' / 'generate-skills'), *args],
        capture_output=True,
        text=True,
        check=False,
    )


def _write_agent(repo: Path, name: str, body: str | None = None) -> Path:
    agent_dir = repo / 'agents' / name
    agent_dir.mkdir(parents=True, exist_ok=True)
    md = agent_dir / f'{name}.md'
    md.write_text(
        body
        or (
            f'---\nname: {name}\ndescription: stub\n---\n\n# {name}\n\nbody\n'
        ),
        encoding='utf-8',
    )
    return md


# --------------------------------------------------------------------------- #
# Empty-tree
# --------------------------------------------------------------------------- #


def test_help_lists_dry_run_and_target_dir(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    result = _run(repo, '--help')
    assert result.returncode == 0, result.stderr
    assert '--dry-run' in result.stdout
    assert '--target-dir' in result.stdout


def test_empty_tree_exits_zero_and_does_not_touch_target(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    target = tmp_path / 'out'
    target.mkdir()

    result = _run(repo, '--target-dir', str(target))

    assert result.returncode == 0, result.stderr
    assert 'Found 0 agents, 0 skills — nothing to generate' in result.stdout
    assert list(target.iterdir()) == []


# --------------------------------------------------------------------------- #
# Fixture-tree
# --------------------------------------------------------------------------- #


def test_single_agent_materializes_skill_md(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _write_agent(repo, 'cast-foo')
    target = tmp_path / 'out'

    result = _run(repo, '--target-dir', str(target))

    assert result.returncode == 0, result.stderr
    out = target / 'cast-foo' / 'SKILL.md'
    assert out.exists()
    content = out.read_text(encoding='utf-8')
    # Generated header + back-reference
    assert 'Generated by bin/generate-skills' in content
    assert 'Source: agents/cast-foo/cast-foo.md' in content
    # Original frontmatter preserved
    assert 'name: cast-foo' in content
    assert 'description: stub' in content


def test_skill_under_claude_code_is_materialized(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    skill_dir = repo / 'skills' / 'claude-code' / 'cast-bar'
    skill_dir.mkdir(parents=True)
    (skill_dir / 'SKILL.md').write_text(
        '---\nname: cast-bar\ndescription: skill stub\n---\n\nhello\n',
        encoding='utf-8',
    )
    target = tmp_path / 'out'

    result = _run(repo, '--target-dir', str(target))

    assert result.returncode == 0, result.stderr
    out = target / 'cast-bar' / 'SKILL.md'
    assert out.exists()
    content = out.read_text(encoding='utf-8')
    assert 'Source: skills/claude-code/cast-bar/SKILL.md' in content


def test_non_cast_subdir_is_skipped_with_warning(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _write_agent(repo, 'cast-foo')
    rogue = repo / 'agents' / 'gemini-shim'
    rogue.mkdir()
    (rogue / 'gemini-shim.md').write_text('---\nname: gemini-shim\n---\n', encoding='utf-8')
    target = tmp_path / 'out'

    result = _run(repo, '--target-dir', str(target))

    assert result.returncode == 0, result.stderr
    assert 'gemini-shim' in result.stderr
    assert 'skipped non-cast-*' in result.stderr
    assert (target / 'cast-foo' / 'SKILL.md').exists()
    assert not (target / 'gemini-shim').exists()


def test_dry_run_writes_nothing(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _write_agent(repo, 'cast-foo')
    target = tmp_path / 'out'
    target.mkdir()

    result = _run(repo, '--target-dir', str(target), '--dry-run')

    assert result.returncode == 0, result.stderr
    assert 'would write' in result.stdout
    # target dir still untouched
    assert list(target.iterdir()) == []


# --------------------------------------------------------------------------- #
# Idempotency
# --------------------------------------------------------------------------- #


def test_idempotent_second_run_produces_no_diff(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _write_agent(repo, 'cast-foo')
    target = tmp_path / 'out'

    first = _run(repo, '--target-dir', str(target))
    assert first.returncode == 0
    skill = target / 'cast-foo' / 'SKILL.md'
    snapshot = skill.read_text(encoding='utf-8')

    second = _run(repo, '--target-dir', str(target))
    assert second.returncode == 0
    assert skill.read_text(encoding='utf-8') == snapshot

    # Only the cast-foo dir + (at most) backup folders should exist.
    top_level = {p.name for p in target.iterdir()}
    assert 'cast-foo' in top_level
    # Pre-existing target file from run 1 was backed up by run 2 — backup folder
    # is acceptable, but no other cast-* dirs.
    cast_dirs = {n for n in top_level if n.startswith('cast-')}
    assert cast_dirs == {'cast-foo'}


# --------------------------------------------------------------------------- #
# Backup-on-overwrite
# --------------------------------------------------------------------------- #


def test_existing_target_file_is_backed_up_before_overwrite(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _write_agent(repo, 'cast-foo')
    target = tmp_path / 'out'
    pre_existing = target / 'cast-foo' / 'SKILL.md'
    pre_existing.parent.mkdir(parents=True)
    pre_existing.write_text('# user manual edit\n', encoding='utf-8')

    result = _run(repo, '--target-dir', str(target))

    assert result.returncode == 0, result.stderr
    # Original file overwritten
    assert 'user manual edit' not in pre_existing.read_text(encoding='utf-8')
    # Backup folder exists with the original content preserved
    backup_dirs = sorted(target.glob('.cast-bak-*'))
    assert len(backup_dirs) == 1
    backed = backup_dirs[0] / 'cast-foo' / 'SKILL.md'
    assert backed.exists()
    assert backed.read_text(encoding='utf-8') == '# user manual edit\n'


def test_single_timestamp_per_invocation(tmp_path: Path) -> None:
    """All backups from one run land in one .cast-bak-<ts>/ folder."""
    repo = _make_repo(tmp_path)
    _write_agent(repo, 'cast-foo')
    _write_agent(repo, 'cast-bar')
    target = tmp_path / 'out'
    for name in ('cast-foo', 'cast-bar'):
        f = target / name / 'SKILL.md'
        f.parent.mkdir(parents=True)
        f.write_text(f'# old {name}\n', encoding='utf-8')

    result = _run(repo, '--target-dir', str(target))
    assert result.returncode == 0, result.stderr

    backup_dirs = sorted(target.glob('.cast-bak-*'))
    assert len(backup_dirs) == 1
    bak = backup_dirs[0]
    assert (bak / 'cast-foo' / 'SKILL.md').exists()
    assert (bak / 'cast-bar' / 'SKILL.md').exists()


def test_no_backup_when_target_is_empty(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _write_agent(repo, 'cast-foo')
    target = tmp_path / 'out'

    result = _run(repo, '--target-dir', str(target))

    assert result.returncode == 0
    assert sorted(target.glob('.cast-bak-*')) == []


# --------------------------------------------------------------------------- #
# Safety
# --------------------------------------------------------------------------- #


def test_target_dir_default_is_under_home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The default target resolves under the caller's $HOME — never CWD-relative."""
    repo = _make_repo(tmp_path)
    # Sanity: --help output mentions ~/.claude/skills as the default
    result = _run(repo, '--help')
    assert '~/.claude/skills' in result.stdout
